backend:
  name: github
  repo: phildaponte/Creative-jekyll # Path to your Github repository
  branch: master # Branch to update

media_folder: "../img/uploads"
public_folder: "../img" # The src attribute for uploaded media will begin with /images/uploads