backend:
  name: github
  # Path to your Github repository (blanked out on purpose)
  branch: optimize # Branch to update

publish_mode: editorial_workflow
media_folder: "src/assets/images/featured"
public_folder: "assets/images" # The src attribute for uploaded media will begin with /images/uploads